name             'demo-kibana'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures demo-kibana'
long_description 'Installs/Configures demo-kibana'
version          '0.1.0'

depends 'java'
depends 'elasticsearch'
